const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.join(__dirname, "..");
const source = fs.readFileSync(path.join(root, "sac-prevencao-v12.js"), "utf8");
const media = fs.readFileSync(path.join(root, "sac-media-v12.js"), "utf8");

assert.match(source, /const BUILD_VERSION = "12\.0"/);
assert.match(source, />Modo investigação</);
assert.match(source, />Modo ajuda</);
assert.match(source, /data-action="help-mode"/);
assert.match(source, /getHelpMode/);
assert.match(source, /<span>Analisar<\/span>/);
assert.match(source, /<span>Ajuda<\/span>/);
assert.match(source, /left:-92px/);
assert.match(source, /\.sac-investigation-launcher\.sac-help-launcher\{top:84px\}/);
assert.match(source, /\.sac-investigation-launcher\.sac-help-launcher\.sac-solo-launcher\{top:48px\}/);
assert.doesNotMatch(source, /requestAnimationFrame\(\(\) => toggleDrawer/);
assert.doesNotMatch(source, /getInvestigationMode\(\) \? transactionEngine\.collectFalconTransactions/);
assert.match(source, /attachInvestigationLauncher\(panel, "FALCON", data, \(\) => transactionEngine\.collectFalconTransactions/);
assert.match(source, /\["FALCON", "CONSOLE", "TABULADOR"\]\.includes\(stage\)/);
assert.match(source, /attachInvestigationLauncher\(panel, "CONSOLE", data\)/);
assert.match(source, /attachInvestigationLauncher\(panel, "TABULADOR", data\)/);
assert.match(source, /INFORMAÇÕES DIVERGENTES, VERIFIQUE O CASO NOVAMENTE/);
assert.doesNotMatch(source, /CASO DIVERGENTE, CONFIRA O FALCON NOVAMENTE/);
assert.match(source, /investigationHelpOverview\(data, stage\)/);
assert.match(source, /sac-help-drawer/);
assert.match(source, /sac-solo-launcher/);
assert.match(source, /\.sac-help-drawer \.sac-side-body/);
assert.doesNotMatch(source, /panel\.addEventListener\("mouseover"/);
assert.doesNotMatch(source, /requestAnimationFrame\(\(\) => drawer\.querySelectorAll\("\[data-investigation\]"\)/);
assert.match(source, /data-investigation-content/);
assert.match(source, />Transacional<\/button>/);
assert.match(source, />CNPJ<\/button>/);
assert.match(source, />Mídias<\/button>/);
assert.doesNotMatch(source, /data-investigation="help"/);
assert.match(source, /Pontos de análise do book/);
assert.match(source, /pelo menos dois indícios concretos/);
assert.match(source, /sac-investigation-heading/);
assert.match(source, /sac-investigation-chevron/);
assert.match(source, /sac-launcher-icon/);
assert.match(source, /aria-expanded/);
assert.match(source, /const launcherReserve = sidePanel\.matches\("\.sac-investigation-drawer,\.sac-help-drawer,\.sac-context-drawer"\) \? 100 : 0/);
assert.doesNotMatch(source, /Transacionando com/);
assert.match(source, /P2P Emissor/);
assert.match(source, /P2P Pessoal/);
assert.match(source, /Dentro de \$\{escapeHtml\(period\)\}/);
assert.match(source, /Padrões transacionais/);
assert.match(source, /Possível triangulação/);
assert.match(source, /Tentativas barradas/);
assert.match(source, /Teste seguido de valor elevado/);
assert.doesNotMatch(source, /<strong>Valor mediano<\/strong>/);
assert.match(source, /Horário suspeito/);
assert.match(source, /Porte da empresa/);
assert.doesNotMatch(source, /Resumo para decisão/);
assert.doesNotMatch(source, /Origem da consulta/);
assert.doesNotMatch(source, /Conferência Falcon x Console/);
assert.doesNotMatch(source, /sac-context-help/);
assert.match(source, /data-remove-counterparty/);
assert.match(source, /data-classify-counterparty="UNTRUSTED"/);
assert.match(source, /data-counterparty-state/);
assert.match(source, /data-cnpj-copy/);
assert.match(source, /cnpjCopyBound/);
assert.match(source, /if \(!card \|\| !getSafeMode\(\)\) return/);
assert.match(source, /\.sac-cnpj-selector strong\{color:var\(--sac-muted\);font-size:calc\(7\.6px \* var\(--sac-font-scale\)\)/);
assert.match(source, />Confiável<\/button>/);
assert.match(source, />Suspeito<\/button>/);
assert.match(source, /function corporateCandidates/);
assert.match(source, /EXCLUIR GRUPO/);
assert.match(source, /removeListIssuerGroup/);
assert.match(source, /data-pid-reload/);
assert.doesNotMatch(source, /Vencimento da fatura/);
assert.doesNotMatch(source, /pidResult/);
assert.match(source, /releaseInvestigationSession/);
assert.match(source, /transferableCaseData/);
assert.match(source, /clearCompletedCaseState/);
assert.match(source, /const CARD_REVIEW = \["não", "sim", "reconhece a compra", "autofinanciamento", "ausência de dados"\]/);

assert.match(media, /function collectCustomerIdentity/);
assert.match(media, /function collectPidData/);
assert.match(media, /queryResult_addressData/);
assert.doesNotMatch(media, /queryResult_phoneData/);

console.log("OK - investigação e ajuda independentes na V12 validadas");
